<?php

/**
 * @file
 * Provides the Foundation Orbit javascript library and styles to the RE Context
 * Libraries module.
 */


// Constants:
define('RE_ORBIT_MODULE_MACHINE_NAME', 're_orbit');
define('RE_ORBIT_LIBRARY_MACHINE_NAME', 're_orbit');
define('RE_ORBIT_LIBRARY_TITLE', 'Foundation Orbit slider (provided by: re_orbit)');


/**
 * Implements hook_define_re_contextlibraries_library().
 */
function re_orbit_define_re_contextlibraries_library() {
  return array(RE_ORBIT_MODULE_MACHINE_NAME . ':' . RE_ORBIT_LIBRARY_MACHINE_NAME => t(RE_ORBIT_LIBRARY_TITLE));
} // re_orbit_define_re_contextlibraries_library()


/**
 * Implements hook_library().
 *
 * Used to register libraries with the system.
 *
 * @todo Figure out why dependencies do NOT work here.
 */
function re_orbit_library() {
  $path_to_module = drupal_get_path('module', RE_ORBIT_MODULE_MACHINE_NAME);
  $libraries[RE_ORBIT_LIBRARY_MACHINE_NAME] = array(
    'title' => RE_ORBIT_LIBRARY_TITLE,
    'website' => 'http://foundation.zurb.com/docs/orbit.php',
    'version' => '1.4.0',
    'js' => array(
      $path_to_module . '/js/jquery.orbit-1.4.0.min.js' => array(
        'group' => JS_LIBRARY,
        'weight' => 4,
      ),
      $path_to_module . '/js/re_orbit.js' => array(
        'group' => JS_LIBRARY,
        'weight' => 6,
      ),
    ),
    'css' => array(
      $path_to_module . '/css/orbit.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
      $path_to_module . '/css/re_orbit.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
    //'dependencies' => array('re_contextlibraries', 're_contextlibraries'),
  );
  return $libraries;
} // re_orbit_library()