<?php

/*
 * implimentation of hook_install
 *
 * we are removing the default theme as we set that in code
 * we also enable the openpublic_theme so it can become default
 */
function datapublic_defaults_install() {
  // we are setting this variables as the appear to get pulled
  // before strongarm can set them
  variable_set("theme_default", "datapublic_theme");
  variable_set("admin_theme", "rubik");
  variable_set("node_admin_theme", '1');
  theme_enable(array("datapublic_theme"));
}